version: '3.9'

services:
  app:
    image: app:latest
    restart: always
    container_name: app
    ports:
      - 5000:5000
    depends_on: 
      - db
    
  db:
    image: postgres
    restart: always
    container_name: my_contacts_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=codeDB

    ports:
      - 5432:5432

    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local

networks:
  chapeira_network:
    driver: bridge